"""Acceptance checks on projects generated by real agent runs (Claude Code and Codex) using the M3 Skills.

The fixtures under tests/fixtures/m3 are snapshots of those runs; transcripts are in tests/fixtures/m3/transcripts.
They are not synthetic: nothing here regenerates them. See docs/SDLC-M3-EVIDENCE.md for how each was produced.
"""

import re
import shutil
from pathlib import Path

import pytest

from conftest import Sandbox
from sdlc import frontmatter

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "m3"
NAMES = sorted(p.name for p in FIXTURES.iterdir() if p.is_dir() and p.name != "transcripts")
NO_SOURCE = re.compile(r"### Derived From\s+- None identified\.")
REQ = re.compile(r"^- \*\*((?:BR|PR)-\d{3}-R\d{3})\*\* — (.+)$", re.M)


@pytest.fixture
def fx(request, tmp_path, capsys, monkeypatch):
    def open_(name):
        root = tmp_path / name
        shutil.copytree(FIXTURES / name, root)
        return Sandbox(root, capsys, monkeypatch)
    return open_


def meta(path: Path) -> dict:
    return frontmatter.parse(frontmatter.split(path.read_text())[0])


def docs(sb, folder):
    return sorted((sb.root / folder).glob("*-*.md"))


def notices(sb, data):
    return {(d["code"], d["id"]) for d in sb.diags(data, severity="notice")}


@pytest.mark.parametrize("name", NAMES)
def test_every_fixture_validates_without_errors_or_warnings_and_maps_are_fresh(name, fx):
    sb = fx(name)
    code, data, _ = sb.run("validate")
    assert code == 0, data["diagnostics"]
    assert data["result"]["summary"]["error"] == 0 and data["result"]["summary"]["warning"] == 0
    assert not sb.diags(data, "stale-map")
    before = sb.snapshot()
    sb.ok("update-map")
    assert sb.snapshot() == before  # maps already reflect metadata


@pytest.mark.parametrize("name", NAMES)
def test_no_template_leftovers_and_only_human_approvals(name, fx):
    sb = fx(name)
    for path in list(sb.root.rglob("*.md")):
        text = path.read_text()
        assert "{{" not in text and "<!--\nBRD template" not in text, path
    approved = {p.name for folder in ("BR", "PR", "Stories") for p in docs(sb, folder) if meta(p)["status"] == "Approved"}
    # Approved appears only where the fixture setup records an explicit human approval (approved-revision, US-001 there)
    assert approved <= ({"US-001-import-appointments-via-csv.md"} if name == "approved-revision" else set())


@pytest.mark.parametrize("name", NAMES)
def test_authored_documents_have_units_the_skills_promise(name, fx):
    sb = fx(name)
    for folder in ("BR", "PR", "Stories"):
        for path in docs(sb, folder):
            m = meta(path)
            assert path.name.startswith(m["id"] + "-") and m["purpose"].strip() and "\n" not in m["purpose"].strip()
            assert re.search(r"^## References$", path.read_text(), re.M)
            if folder == "Stories":
                assert m["delivery_status"] in ("Not Started", "Ready", "In Progress")  # never Implemented/Verified in M3
                assert re.search(r"(?i)given.*when.*then", path.read_text())


def test_sparse_idea_becomes_substantive_brd_with_visible_unknowns(fx):
    sb = fx("brd-standalone")
    (path,) = docs(sb, "BR")
    text = path.read_text()
    assert meta(path)["status"] == "Draft" and meta(path)["id"] == "BR-001"
    for heading in ("Business Context and Problem", "Objectives and Desired Outcomes", "Stakeholders", "Scope",
                    "Business Requirements", "Constraints and Dependencies", "Success Measures",
                    "Assumptions and Risks", "Open Questions"):
        assert f"## {heading}" in text, heading
    reqs = REQ.findall(text)
    assert [r[0] for r in reqs] == [f"BR-001-R00{i}" for i in range(1, len(reqs) + 1)] and len(reqs) >= 3
    assert len(text) > 2500
    # the user answered "TBD"/"unknown" to targets, budget and regulations: they must stay unknown
    assert re.search(r"Target: TBD", text) and "Budget: TBD" in text and "Unknown" in text
    assert "HIPAA" not in text.split("## Business Requirements")[1].split("## Constraints")[0]  # user asked for it removed
    assert not re.search(r"\b\d+\s?%", text.replace("15%", ""))  # no invented percentages beyond the user's 15%
    assert "| BR-001 |" in (sb.root / "BR" / "map.md").read_text()


def test_prd_with_brd_links_source_and_uses_pr_ids(fx):
    sb = fx("prd-with-brd")
    (prd,) = docs(sb, "PR")
    (brd,) = docs(sb, "BR")
    text = prd.read_text()
    assert f"- [BR-001 — {meta(brd)['title']}](../BR/{brd.name})" in text
    assert (prd.parent / f"../BR/{brd.name}").resolve().is_file()
    ids = [r[0] for r in REQ.findall(text)]
    assert ids == [f"PR-001-R00{i}" for i in range(1, len(ids) + 1)] and len(ids) >= 5
    for heading in ("Product Summary", "Target Users and Needs", "User Journeys and Use Cases", "Behavior and Capabilities",
                    "Scope", "Product Requirements", "Acceptance Expectations", "Constraints and Dependencies"):
        assert f"## {heading}" in text
    assert "BR-001" in (sb.root / "PR" / "map.md").read_text() and "Derived From" in (sb.root / "PR" / "map.md").read_text()
    assert "TBD" in text and "Unknown" in text  # unanswered consent/failure questions preserved


def test_prd_without_brd_is_independent(fx):
    sb = fx("prd-standalone")
    (prd,) = docs(sb, "PR")
    assert docs(sb, "BR") == []
    text = prd.read_text()
    assert NO_SOURCE.search(text)
    assert len(REQ.findall(text)) >= 5
    data = sb.ok("validate")
    assert data["result"]["summary"]["error"] == 0
    assert "TBD" in text  # offline, notifications, quantities left open


def test_stories_are_traceable_distinct_and_observable(fx):
    sb = fx("stories-full")
    stories = docs(sb, "Stories")
    assert len(stories) == 6
    prd = docs(sb, "PR")[0]
    prd_ids = {r[0] for r in REQ.findall(prd.read_text())}
    covered, titles, scopes = set(), set(), set()
    for s in stories:
        m, text = meta(s), s.read_text()
        assert set(m["covers"]) <= prd_ids  # only real requirement IDs, never document IDs
        assert not any(c.count("-") == 1 for c in m["covers"])
        if m["covers"]:
            assert f"](../PR/{prd.name})" in text.split("### Related To")[0]  # owning document linked under Derived From
        covered |= set(m["covers"])
        titles.add(m["title"])
        scopes.add(text.split("### In Scope")[1].split("###")[0].strip())
        assert len(re.findall(r"(?im)^\d+\. .*given.*when.*then", text)) >= 1
        assert "## Edge Cases and Negative Paths" in text
    assert len(titles) == 6 and len(scopes) == 6
    assert covered == prd_ids  # every requirement covered by some Story
    data = sb.ok("validate")
    assert notices(sb, data) == {("story-no-coverage", "US-006")}  # the one standalone Story
    assert data["exit_code"] == 0


def test_standalone_story_has_empty_covers_and_notice_only(fx):
    sb = fx("stories-full")
    story = next(s for s in docs(sb, "Stories") if meta(s)["id"] == "US-006")
    assert meta(story)["covers"] == []
    code, data, _ = sb.run("validate")
    assert code == 0 and [d for d in data["diagnostics"] if d["id"] == "US-006"][0]["severity"] == "notice"


def test_overlap_revise_branch_keeps_single_document_and_stable_ids(fx):
    sb = fx("overlap-revised")
    (path,) = docs(sb, "BR")
    assert meta(path)["id"] == "BR-001" and meta(path)["status"] == "Draft"
    ids = [r[0] for r in REQ.findall(path.read_text())]
    assert ids == [f"BR-001-R00{i}" for i in range(1, 8)]  # R001-R005 preserved, R006-R007 added
    ledger = (sb.root / ".sdlc" / "ledger.md").read_text()
    assert "BR-002 " not in ledger  # no second document was allocated
    assert "reminder timing rules" not in path.read_text().lower().split("## open questions")[1]  # resolved question removed


def test_overlap_new_branch_creates_second_document_and_leaves_first_untouched(fx):
    sb = fx("overlap-new")
    first, second = docs(sb, "BR")
    assert (meta(first)["id"], meta(second)["id"]) == ("BR-001", "BR-002")
    assert meta(first)["updated"] == "2026-09-29" and len(REQ.findall(first.read_text())) == 5  # first document unchanged
    assert first.name in second.read_text()  # related link to the existing BRD
    assert meta(second)["title"] != meta(first)["title"]


def test_approved_documents_return_to_in_review_only_on_material_edit(fx):
    sb = fx("approved-revision")
    brd = docs(sb, "BR")[0]
    us1, us3 = (next(s for s in docs(sb, "Stories") if meta(s)["id"] == i) for i in ("US-001", "US-003"))
    # material edits (new requirement / new acceptance criterion) reset approval and bump `updated`
    assert (meta(brd)["status"], meta(brd)["updated"], meta(brd)["created"]) == ("In Review", "2026-09-29", "2026-09-01")
    assert "BR-001-R006" in brd.read_text()
    assert (meta(us3)["status"], meta(us3)["updated"]) == ("In Review", "2026-09-29")
    assert "cancelled" in us3.read_text()
    # no material change was made to US-001, so its approval stands
    assert (meta(us1)["status"], meta(us1)["updated"]) == ("Approved", "2026-09-01")
    assert "In Review" in (sb.root / "BR" / "map.md").read_text() and "In Review" in (sb.root / "Stories" / "map.md").read_text()


def test_removed_requirement_is_tombstoned_and_stories_reconciled(fx):
    sb = fx("removed-requirement")
    ledger = (sb.root / ".sdlc" / "ledger.md").read_text()
    assert re.search(r"\| PR-001-R002 \| requirement \| Retired \|", ledger)
    prd = docs(sb, "PR")[0]
    assert "**PR-001-R002**" not in prd.read_text() or "Retired" in prd.read_text()
    us2 = next(s for s in docs(sb, "Stories") if meta(s)["id"] == "US-002")
    assert meta(us2)["covers"] == [] and "PR-001-R002" not in str(meta(us2)["covers"])
    data = sb.ok("validate")
    assert not sb.diags(data, "retired-reference") and ("story-no-coverage", "US-002") in notices(sb, data)
    assert sb.ok("allocate-id", "--requirement", "PR-001")["result"]["id"] == "PR-001-R007"  # R002 never recycled


def test_codex_generated_projects_meet_the_same_contract(fx):
    sb = fx("codex-prd-stories")
    prd = docs(sb, "PR")[0]
    prd_ids = {r[0] for r in REQ.findall(prd.read_text())}
    stories = docs(sb, "Stories")
    assert len(stories) == 4 and NO_SOURCE.search(prd.read_text())
    assert set().union(*[set(meta(s)["covers"]) for s in stories]) == prd_ids
    data = sb.ok("validate")
    assert notices(sb, data) == set()
    brd = fx("codex-brd")
    (path,) = docs(brd, "BR")
    assert meta(path)["status"] == "Draft" and "TBD" in path.read_text() and len(REQ.findall(path.read_text())) >= 3
    assert re.search(r"estimate", path.read_text(), re.I)  # the user's unverified 10% figure is labeled as an estimate


def test_transcripts_are_present_for_each_discipline():
    t = FIXTURES / "transcripts"
    names = {p.stem for p in t.glob("*.md")}
    assert {"s1-brd", "s2-prd-with-brd", "s3-prd-standalone", "s4-stories", "s6-overlap", "s6-overlap-new",
            "s8-approved-revision", "s9-removed-requirement", "c1-codex-prd", "c1-codex-stories", "c2-codex-brd",
            "d1-claude-md-approved", "d2-agents-md-approved", "d3-overlap-verbatim", "d4-recap",
            "h1-contextual-brd", "h2-contextual-prd", "h3-contextual-stories"} <= names


GWT_TBD = re.compile(r"(?i)\bthen\b.*\b(TBD|unknown|undecided|not yet decided)\b")


@pytest.mark.parametrize("name", NAMES)
def test_unresolved_outcomes_are_never_written_as_executable_criteria(name, fx):
    sb = fx(name)
    for path in docs(sb, "Stories"):
        text = path.read_text()
        for section in ("## Acceptance Criteria", "## Edge Cases and Negative Paths"):
            if section in text:
                body = text.split(section)[1].split("\n## ")[0]
                for line in body.split("\n"):
                    if re.search(r"(?i)\bgiven\b", line) and re.search(r"(?i)\bwhen\b", line):
                        assert not GWT_TBD.search(line), f"{path.name}: {line[:90]}"
                    if line.lstrip().startswith("- **TBD**"):
                        assert not re.search(r"(?i)\*\*then\*\*", line), path.name


def test_standalone_prd_corrections_hold(fx):
    sb = fx("prd-standalone")
    text = docs(sb, "PR")[0].read_text()
    assert "including who is shown as having added it is not yet decided" not in text
    assert "Whether the list shows who added or bought each item is not yet decided" in text
    assert "unknowingly" not in text and "add the same item" not in text  # duplicate prevention was never established
    # the shared-list expectations the user did establish remain
    acceptance = text.split("## Acceptance Expectations")[1].split("## Constraints")[0]
    assert "visible to every other member" in acceptance and "bought section" in acceptance


@pytest.mark.parametrize("scenario,category,title,purpose", [
    ("brd-standalone", "BR", "Automated appointment reminders for independent clinics", "Send patients reminders to cut no-shows"),
    ("prd-with-brd", "PR", "Patient notification service for clinics", "Notify patients ahead of appointments by text and email"),
    ("stories-full", "US", "Front desk confirms a patient received the reminder", "Let staff check whether a patient got their reminder"),
])
def test_contextual_review_covers_what_the_lexical_cli_misses(scenario, category, title, purpose, fx):
    """The hardening rationale, pinned: these same-topic requests score below the CLI threshold, which is why the
    Skills add an unscored contextual review (agent transcripts h1/h2/h3 show it firing)."""
    sb = fx(scenario)
    r = sb.ok("find-overlaps", "--category", category, "--title", title, "--purpose", purpose)["result"]
    assert r["candidates"] == [] and r["action"] == "none"
    assert len(sb.ok("list", "--category", category)["result"]["documents"]) >= 1  # candidates exist for the agent to judge


def test_contextual_relate_result_links_new_document_and_leaves_original_untouched():
    """Snapshot check on the agent-run `relate` branch is in the transcript; here assert the transcript shows the
    unscored separate presentation and the three-way choice before any allocation."""
    t = (FIXTURES / "transcripts" / "h1-contextual-brd.md").read_text()
    first = t.split("### USER")[1]
    assert "Conceptual overlaps (my judgement, not CLI-scored)" in first
    assert "**Revise**" in first and "**Relate**" in first and "**Create new**" in first
    assert not re.search(r"\b0\.\d+\b|\d+\s?%", first.split("Conceptual overlaps")[1])  # no invented similarity number
    assert "won't allocate an ID" in first
